config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :breeds
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  namespace :api do
    namespace :vi do
      resources :breeds
    end
  end
  get '*path', to: 'home#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
    has_many :cats
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :breed
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /breeds or /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1 or /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds or /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to breed_url(@breed), notice: "Breed was successfully created." }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1 or /breeds/1.json
  def update
    if @breed.update(breed_params)
      redirect_to breeds_url(@breed)
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1 or /breeds/1.json
  def destroy
    begin
      @breed.destroy

      respond_to do |format|
        format.html { redirect_to breeds_url, notice: "Breed was successfully destroyed." }
        format.json { head :no_content }
      end

      rescue ActiveRecord::InvalidForeignKey => e
        respond_to do |format|
          format.html {redirect_to breeds_url, alert: "Cannot delete breed that existing cat belongs to."}
          format.json { head :no_content }
        end
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breed_params
      params.require(:breed).permit(:name, :description, :rare, :image_url)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /cats or /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :age, :gender, :image_url, :breed_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/breeds/_form.html.erb
<%= form_with(model: breed) do |form| %>
  <% if breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
        <% breed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field my-2">
      <%= form.label :name, "Name:", class: "text-white font-bold" %>
      <%= form.text_field :name, class: "bg-gray-800 text-white p-2 rounded border border-gray-600 w-full" %>
    </div>

    <div class="field flex flex-row">
      <%= form.label :rare, "Rare:", class: "text-white font-bold mr-2" %>
      <%= form.check_box :rare %>
    </div>

  <div class="field mb-2">
    <%= form.label :description, "Description:", class: "text-white font-bold"  %>
    <%= form.text_area :description, class: "bg-gray-800 text-white p-2 ml-2 rounded border border-gray-600 w-full" %>
  </div>

  <div class="field">
    <%= form.label :image_url, "Image URL:", class: "text-white font-bold" %>
    <%= form.text_field :image_url, class: "bg-gray-800 text-white p-2 rounded border border-gray-600 w-full" %>
  </div>

  <div class="actions flex justify-center items-center mt-4">
    <%= form.submit "Update Breed", class: "btn btn-green" %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<div class="card-wrapper-container">
    <div class="card-title-container">
    <span class="card-title">
        Editing <%= @breed.name %>
    </span>
    </div>
    <div class="card-main-container flex-1 flex-col p-4 justify-center items-center">
        <%= react_component("EditBreed", {auth_token: form_authenticity_token, breed: @breed.as_json}) %>
        <%= render 'form', breed: @breed %>
        <div class="mt-4">
            <%= link_to 'Show', @breed, class: "btn btn-yellow" %>
            <%= link_to 'Back', breeds_path, class: "btn btn-purple" %>
        </div>
    </div>
</div>

app/views/breeds/index.html.erb
<div style="min-height: 100vh">
  <%= react_component('Breeds', {auth_token: form_authenticity_token}) %>
</div>

app/views/breeds/new.html.erb
<h1>New Breed</h1>

<%= render 'form', breed: @breed %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<div class="card-wrapper-container">
  <div class="card-title-container">
    <span class="card-title">
      <%= @breed.name %>
    </span>
  </div>
  <div class="card-main-container flex flex-col p-4 justify-center items-center">
    <div class="flex">
      <div class="w-1/2 mr-4">
        <p class="text-white">
          <strong>Rare:</strong> <br>
          <%= @breed.rare %>
        </p>
        <br/>
        <p class="text-white">
          <strong>Description:</strong> <br>
          <%= @breed.description %>
        </p>
      </div>
      <div class="w-1/2">
        <img src="<%= @breed.image_url %>" alt="breed image">
      </div>
    </div>

    <div class="mt-4">
      <%= link_to 'Edit', edit_breed_path(@breed), class: "btn btn-yellow" %>
      <%= link_to 'Back', breeds_path, class: "btn btn-purple" %>
    </div>
  </div>
</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field my-2">
      <%= form.label :name, "Name:", class: "text-white font-bold" %>
      <%= form.text_field :name, class: "bg-gray-800 text-white p-2 rounded border border-gray-600 w-full" %>
    </div>

    <div class="field mb-2">
      <%= form.label :age, "Age:", class: "text-white font-bold mr-2" %>
      <%= form.number_field :age, class: "bg-gray-800 text-white p-2 ml-2 rounded border border-gray-600 w-full" %>
    </div>

  <div class="field mb-2">
    <%= form.label :gender, "Gender:", class: "text-white font-bold"  %><br>
    <div class="flex">
      <div class="flex flex-col items-center justify-center mr-4">
        <%= form.radio_button :gender, 'Female' %>
        <%= form.label :gender, "Female", :value => "female", class: "text-white" %>
      </div>
      <div class="flex flex-col items-center justify-center">
        <%= form.radio_button :gender, 'Male' %>
        <%= form.label :gender, "Male", :value => "male", class: "text-white"  %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :breed_id, "Breed:", class: "text-white font-bold" %>
    <%= form.text_field :breed_id, class: "bg-gray-800 text-white p-2 rounded border border-gray-600 w-full" %>
  </div>

  <div class="field">
    <%= form.label :image_url, "Image URL:", class: "text-white font-bold" %>
    <%= form.text_field :image_url, class: "bg-gray-800 text-white p-2 rounded border border-gray-600 w-full" %>
  </div>

  <div class="actions flex justify-center items-center mt-4">
    <%= form.submit "Update Breed", class: "btn btn-green" %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<div class="card-wrapper-container">
<div class="card-title-container">
<span class="card-title">
    Editing <%= @cat.name %>
</span>
</div>
<div class="card-main-container flex-1 flex-col p-4 justify-center items-center">
    <%= render 'form', cat: @cat %>
    <div class="mt-4">
        <%= link_to 'Show', @cat, class: "btn btn-yellow" %>
        <%= link_to 'Back', cats_path, class: "btn btn-purple" %>
    </div>
</div>
</div>

app/views/cats/index.html.erb
<div class="card-wrapper-container">
<div class="card-title-container">
  <span class="card-title">
    Cats
  </span>
</div>
<div class="card-main-container flex flex-col">
  <table class="grid-table mx-10 my-3 table-fixed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Breed</th>
        <th class="text-center w-64">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @cats.each do |cat| %>
        <tr>
          <td><%= cat.name %></td>
          <td><%= cat.age %></td>
          <td><%= cat.gender %></td>
          <td><%= cat.breed.name %></td>
          <td class="justify-center flex flex-1">
            <%= link_to 'Show', cat, class: "btn btn-purple" %>
            <%= link_to 'Edit', edit_cat_path(cat), class: "btn btn-dark-purple" %>
            <%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-red" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="justify-end flex">
    <%= link_to '+ New Cat', new_cat_path, class: "btn btn-purple m-2 w-40" %>
  </div>
</div>
</div

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<div class="card-wrapper-container">
<div class="card-title-container">
  <span class="card-title">
    <%= @cat.name %>
  </span>
</div>
<div class="card-main-container flex flex-col p-4 justify-center items-center">
  <div class="flex">
    <div class="w-1/2 mr-4">
      <p class="text-white">
        <strong>Breed:</strong> <br>
        <%= @cat.breed.name %>
      </p>
      <br>
      <p class="text-white">
        <strong>Age:</strong> <br>
        <%= @cat.age %>
      </p>
      <br>
      <p class="text-white">
        <strong>Gender:</strong> <br>
        <%= @cat.gender %>
      </p>
    </div>
    <div class="w-1/2">
      <img src="<%= @cat.image_url %>" alt="cat image">
    </div>
  </div>

  <div class="mt-4">
    <%= link_to 'Edit', edit_cat_path(@cat), class: "btn btn-yellow" %>
    <%= link_to 'Back', cats_path, class: "btn btn-purple" %>
  </div>
</div>
</div>

app/views/layouts/_flash_notices.html.erb
<div id="notices" class="pt-4 px-4 bg-black">
  <% if notice %>
    <div class="border-container-purple"><span class="ml-2 text-gray-900"><%= notice %></span></div>
  <% end %>
  <% if alert %>
    <div class="border-container-yellow"><span class="ml-2 text-gray-900"><%= alert %></span></div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="flex items-center justify-between flex-wrap bg-purple-900 p-6 sticky top-0 z-50 relative">
<div class="flex items-center flex-shrink-0 text-white mr-6">
  <span class="font-bold text-xl">
    <%= link_to "Nekonomicon", root_path, class: "nav-title" %>
  </span>
</div>

<div class="w-full block flex-grow sm:flex sm:items-center sm:w-auto">
    <% if !user_signed_in? %>
    <div class="text-lg sm:flex-grow flex items-center justify-end">
      <%=link_to "Sign up", new_user_registration_path, class: "nav-li text-white" %>
      <%=link_to "Log in", new_user_session_path, class: "nav-li text-white" %>
    <div>
    <% end %>

  <% if user_signed_in? %>
      <div class="text-lg sm:flex-grow flex items-center justify-between">
        <div class="justify-none">
          <%=link_to "Breeds", breeds_path, class: "nav-li" %>
          <%=link_to "Cats", cats_path, class: "nav-li" %>
        </div>

        <div class="items-center flex">
            <%=link_to "Settings", edit_user_registration_path, class: "nav-li float-right" %>
            <%=link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-red float-right text-white" %>
        </div>
      </div>
    <% end %>
    
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nekonomicon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-black">
    <%= render partial: 'layouts/navigation' %>
    <%= render partial: 'layouts/flash_notices' %>
    <div class="p-4">
      <%= yield %>
    </div>
  </body>
</html>